# Generated by Django 3.2.6 on 2021-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_description', models.TextField(verbose_name='Desctiption')),
                ('user_contact_number', models.CharField(max_length=11)),
                ('user_address', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='about/images')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_fullname', models.CharField(max_length=250)),
                ('comment_email', models.EmailField(max_length=250)),
                ('comment_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=100, unique=True)),
                ('contact_address', models.CharField(max_length=11)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
