# Generated by Django 3.2.6 on 2021-08-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user_github_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_instagram_link',
        ),
    ]
