# Generated by Django 3.2.6 on 2021-08-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='about',
            name='user_github_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='user_instagram_link',
            field=models.URLField(default=''),
        ),
    ]
