# Generated by Django 3.2.6 on 2022-04-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/images/'),
        ),
    ]
