# Generated by Django 3.2.6 on 2022-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_address',
            field=models.CharField(default='492 South St. DBP Village, Ma-a, Davao City', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='user_contact_number',
            field=models.CharField(default='0955709557', max_length=11),
        ),
        migrations.AlterField(
            model_name='about',
            name='user_email',
            field=models.EmailField(default='samsabellanojr@gmail.com', max_length=255),
        ),
    ]
