# Generated by Django 3.2.6 on 2021-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210815_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_description',
            field=models.TextField(verbose_name="I'm a backend developer and UI/UX designer."),
        ),
        migrations.AlterField(
            model_name='about',
            name='user_first_name',
            field=models.CharField(default='Samuel', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='user_github_link',
            field=models.URLField(default='https://github.com/samsabellano'),
        ),
        migrations.AlterField(
            model_name='about',
            name='user_instagram_link',
            field=models.URLField(default='https://www.instagram.com/sam.sabellano/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='user_last_name',
            field=models.CharField(default='Sabellano', max_length=255),
        ),
    ]
