# Generated by Django 3.2.6 on 2021-08-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210815_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_description',
            field=models.TextField(default="I'm a backend developer and UI/UX designer."),
        ),
    ]
