# Generated by Django 3.2.6 on 2021-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_about_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='user_github_link',
            field=models.URLField(blank=True, default='https://github.com/samsabellano', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/images'),
        ),
        migrations.AddField(
            model_name='about',
            name='user_instagram_link',
            field=models.URLField(blank=True, default='https://www.instagram.com/sam.sabellano/', null=True),
        ),
    ]
