# Generated by Django 3.2.6 on 2021-08-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_about_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_description',
            field=models.TextField(blank=True, default="I'm a backend developer and UI/UX designer.", null=True),
        ),
    ]
