# Generated by Django 3.2.6 on 2021-08-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_about_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_github_link',
            field=models.URLField(blank=True, default='https://github.com/samsabellano', null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='user_instagram_link',
            field=models.URLField(blank=True, default='https://www.instagram.com/sam.sabellano/', null=True),
        ),
    ]
